name: Update NASA Predictions

on:
  schedule:
    - cron: "0 1 * * *"   # setiap hari jam 08 WIB
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - run: pip install -r requirements.txt

      - run: python update_predictions.py

      - run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add predictions/*.json
          git commit -m "auto: update NASA predictions" || echo "No changes"
          git push
